### ISSUE TITLE
can u help

### ISSUE THREAD

**Issue by smat-al** [dogagcmnr/VFSGlobal#2]
i tried to use it with moroccan vfs global, but in vain
if possible soe hwlps, thanks
<option value="5561">Netherlands Visa application center  Rabat</option>

https://visa.vfsglobal.com/mar/fr/nld

https://row1.vfsglobal.com/GlobalAppointment/Account/RegisteredLogin?q=shSA0YnE4pLF9Xzwon/x/MI24mBrB3J1rBC1vdDKa5IQdrJXKYTs+DdVJBpH9l4lY2LX+h/tM8d8Y/AclbLTh7nO1zRo08G72bxFCAK20jJiBuG9FQQGZwadSZuIooQKBC5FpJ40OxXI/gYQEbPUR/rfAVTj+BLAwbVNjW424rE=

**Comment by smat-al** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Testez le nouveau système multiplateforme PowerShell https://aka.ms/pscore6

PS C:\Users\Soul & Houd\Documents\VFSGlobal-main> & "C:/Users/Soul & Houd/AppData/Local/Programs/Python/Python310/python.exe" "c:/Users/Soul & Houd/Documents/VFSGlobal-main/start.py"
c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py:9: DeprecationWarning: executable_path has been deprecated, please 
pass in a Service object
  browser = webdriver.Chrome(executable_path=driver_path)

DevTools listening on ws://127.0.0.1:8169/devtools/browser/b1d3efe9-c8d1-462d-8fee-5b31892302b8
Traceback (most recent call last):
  File "c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py", line 9, in <module>
    browser = webdriver.Chrome(executable_path=driver_path)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 93, in __init__
    RemoteWebDriver.__init__(
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 92
Current browser version is 103.0.5060.53 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x01265843+2512963]
        Ordinal0 [0x011FEED1+2092753]
        Ordinal0 [0x01101F48+1056584]
        Ordinal0 [0x011201AA+1180074]
        Ordinal0 [0x0111C0C5+1163461]
        Ordinal0 [0x0111990F+1153295]
        Ordinal0 [0x0114994F+1349967]
        Ordinal0 [0x011495BA+1349050]
        Ordinal0 [0x011454BB+1332411]
        Ordinal0 [0x01121D14+1187092]
        Ordinal0 [0x01122B79+1190777]
        GetHandleVerifier [0x013E0C56+1501718]
        GetHandleVerifier [0x0148E97F+2213695]
        GetHandleVerifier [0x012E8C92+485970]
        GetHandleVerifier [0x012E7D59+482073]
        Ordinal0 [0x0120471D+2115357]
        Ordinal0 [0x01208678+2131576]
        Ordinal0 [0x012087B2+2131890]
        Ordinal0 [0x01211971+2169201]
        BaseThreadInitThunk [0x75DFFA29+25]
        RtlGetAppContainerNamedObjectPath [0x779B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x779B7A6E+238]

PS C:\Users\Soul & Houd\Documents\VFSGlobal-main>

**Comment by smat-al** [comment]
how to resolve this problem please?
thanks.

**Comment by smat-al** [comment]
PowerShell 7.2.5
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Users\Soul & Houd\Documents\VFSGlobal-main> & "C:/Users/Soul & Houd/AppData/Local/Programs/Python/Python310/python.exe" "c:/Users/Soul & Houd/Documents/VFSGlobal-main/start.py"
c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py:9: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(executable_path=driver_path)

DevTools listening on ws://127.0.0.1:1134/devtools/browser/bc24cf11-6ae4-4ce9-babd-d44658cc2339
c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py:13: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  mail = browser.find_element_by_xpath(xe)
Traceback (most recent call last):
  File "c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py", line 34, in <module>
    login(xpaths.email, xpaths.password, password.userid, password.pw)
  File "c:\Users\Soul & Houd\Documents\VFSGlobal-main\start.py", line 13, in login
    mail = browser.find_element_by_xpath(xe)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 521, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1248, 
in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Soul & Houd\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="EmailId"]"}
  (Session info: chrome=92.0.4515.107)
Stacktrace:
Backtrace:
        Ordinal0 [0x009B5843+2512963]
        Ordinal0 [0x0094EED1+2092753]
        Ordinal0 [0x00851F48+1056584]
        Ordinal0 [0x0087C70B+1230603]
        Ordinal0 [0x008A6442+1401922]
        Ordinal0 [0x0089562A+1332778]
        Ordinal0 [0x008A487F+1394815]
        Ordinal0 [0x008954BB+1332411]
        Ordinal0 [0x00871D14+1187092]
        Ordinal0 [0x00872B79+1190777]
        GetHandleVerifier [0x00B30C56+1501718]
        GetHandleVerifier [0x00BDE97F+2213695]
        GetHandleVerifier [0x00A38C92+485970]
        GetHandleVerifier [0x00A37D59+482073]
        Ordinal0 [0x0095471D+2115357]
        Ordinal0 [0x00958678+2131576]
        Ordinal0 [0x009587B2+2131890]
        Ordinal0 [0x00961971+2169201]
        BaseThreadInitThunk [0x75DFFA29+25]
        RtlGetAppContainerNamedObjectPath [0x779B7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x779B7A6E+238]

PS C:\Users\Soul & Houd\Documents\VFSGlobal-main> [16188:14668:0626/230528.484:ERROR:device_event_log_impl.cc(214)] [23:05:28.484] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Un priphrique attach au systme ne fonctionne pas correctement. (0x1F)
[16188:14668:0626/230528.486:ERROR:device_event_log_impl.cc(214)] [23:05:28.486] USB: usb_device_handle_win.cc:1048 Failed to read descriptor from node connection: Un priphrique attach au systme ne fonctionne pas correctement. (0x1F)

**Comment by dogagcmnr** [comment]
Hi, i'll take a look at it. It's normal to face such issues as expected layout changes over time.
